apiVersion: forklift.konveyor.io/v1beta1
kind: VSphereXcopyVolumePopulator
metadata:
  name: test-xcopy
  namespace: pop
spec:
  SecretName: populator-secret
  storageVendorProduct: primera3par
  vmdkPath: "[eco-iscsi-ds1] ubuntu-automate-test2/ubuntu-20.04-server-cloudimg-amd64.vmdk"
