apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xcopy-pvc
  namespace: ${.POD_NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  dataSource:
    apiGroup: forklift.konveyor.io
    kind: VSphereXcopyVolumePopulator
    name: test-xcopy
  dataSourceRef:
    apiGroup: forklift.konveyor.io
    kind: VSphereXcopyVolumePopulator
    name: test-xcopy
  resources:
    requests:
      storage: 10Gi
  storageClassName: xcopy-storage-class
  volumeMode: Block

