pod-namespace: pop
test-namespace: vsphere-populator-test
storage-vendor: primera3par
secret-name: populator-secret
kubeconfig: "/home/amit/.kube/config"
test-image-label:  0.38
test-labels: vsphere-populator
test-populator-image: quay.io/amitos/vsphere-xcopy-volume-populator
storage-password: storage
vsphere-password: vsphere
controller-path: assets/manifests/xcopy-setup/controller.yaml